### ISSUE TITLE
Organização do trabalho

### ISSUE THREAD

**Issue by daidson** [LotusAttic/fairytail-aragorn#2]
Criei um arquivo chamado `organizacao.md` no repositório.

Nele, vocês poderão encontrar o que se deve fazer para ajudar na organização do trabalho.
Fora isso, usem a explicação que foi passada na monitoria para desenvolver o código.
Tenham como base o jogo Akernaak, que se encontra no hydra.

Have fun!

**Comment by daidson** [comment]
Favor marcar como ciente após ler esse issue.

A última pessoa a ler deverá fechar o issue.

**Comment by Mechanichs** [comment]
Todos cientes.

**Comment by daidson** [comment]
Favor responder por si e deixar que os outros respondam por eles mesmos, @Mechanichs . Issue reaberta.

**Comment by rafaziz** [comment]
Haviamos marcando a ciencia com o "thumb up", por isso o comentário do Mechanics. Mas iremos demonstrar com comentários

**Comment by rafaziz** [comment]
ciente

**Comment by mayarajuvencio** [comment]
ciente
