### ISSUE TITLE
Mudança de nome do exN.c

### ISSUE THREAD

**Issue by mayarajuvencio** [LotusAttic/fairytail-aragorn#7]
Mudarei o nome de exN.c para exrpg.c

**Comment by mayarajuvencio** [comment]
Nome alterado.

**Comment by daidson** [comment]
@mayarajuvencio sugiro usar uma referência nos seus commits (no próprio hydra) para informar o que foi feito e onde foi feito. isso fica como sugestão para todos os outros também @Rafaziz @Mechanichs
